# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Will' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Will

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Moya', '~> 13.0'
  pod 'XCDYouTubeKit', '~> 2.8.0'
  pod 'Kingfisher', '~> 5.8.3'
  pod 'RxKingfisher', '~> 1.0.0'
  
end
